sonar.projectKey=3d-portfolio
sonar.projectName=3d-portfolio
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=src/assets/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
